services:
  - type: web
    name: chat-application
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: SaurabhChatDB
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: SaurabhChatDB
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: SaurabhChatDB
          property: password
